# Generated by Django 6.0.3 on 2026-04-05 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20)),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('gstin', models.CharField(blank=True, default='', max_length=20, verbose_name='GSTIN')),
                ('tax_type', models.CharField(choices=[('none', 'No Tax'), ('gst', 'GST'), ('cgst_sgst', 'CGST + SGST')], default='none', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Single GST rate %', max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='CGST rate %', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='SGST rate %', max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account', models.CharField(blank=True, default='', max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=20, verbose_name='IFSC Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_address', models.TextField(blank=True, default='')),
                ('client_gstin', models.CharField(blank=True, default='', max_length=20, verbose_name='Client GSTIN')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_type', models.CharField(choices=[('none', 'No Tax'), ('gst', 'GST'), ('cgst_sgst', 'CGST + SGST')], default='none', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
        ),
    ]
