# Generated by Django 6.0.3 on 2026-04-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_businessprofile_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR - Indian Rupee (₹)'), ('$', 'USD - US Dollar ($)'), ('€', 'EUR - Euro (€)'), ('£', 'GBP - British Pound (£)'), ('¥', 'JPY - Japanese Yen (¥)'), ('A$', 'AUD - Australian Dollar (A$)'), ('C$', 'CAD - Canadian Dollar (C$)'), ('CHF', 'CHF - Swiss Franc (CHF)'), ('¥', 'CNY - Chinese Yuan (¥)'), ('₩', 'KRW - South Korean Won (₩)'), ('R', 'ZAR - South African Rand (R)'), ('د.إ', 'AED - UAE Dirham (د.إ)'), ('﷼', 'SAR - Saudi Riyal (﷼)'), ('₿', 'BTC - Bitcoin (₿)')], default='₹', max_length=5),
        ),
    ]
